// Mocks generated by Mockito 5.4.4 from annotations
// in news_app/test/unitest/datasource/home/home_local_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:news_app/features/home/data/datasource/home_local_data_source.dart'
    as _i2;
import 'package:news_app/features/home/data/models/response/article_model.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [HomeLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeLocalDataSource extends _i1.Mock
    implements _i2.HomeLocalDataSource {
  @override
  _i3.Future<String> saveTopHeadlinesLocal(List<_i4.ArticleModel>? articles) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveTopHeadlinesLocal,
          [articles],
        ),
        returnValue: _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #saveTopHeadlinesLocal,
            [articles],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<String>.value(_i5.dummyValue<String>(
          this,
          Invocation.method(
            #saveTopHeadlinesLocal,
            [articles],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<List<_i4.ArticleModel>> getTopHeadlinesLocal() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopHeadlinesLocal,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.ArticleModel>>.value(<_i4.ArticleModel>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.ArticleModel>>.value(<_i4.ArticleModel>[]),
      ) as _i3.Future<List<_i4.ArticleModel>>);
}
