name: news_app
description: "Build a simple news app that allows users to browse the latest news articles. The app should fetch data from the NewsAPI and display it in a user-friendly manner."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  cached_network_image: ^3.4.0
  http: ^1.2.2
  get_it: ^7.7.0
  dio: ^5.5.0+1
  intl: ^0.19.0
  equatable: ^2.0.5
  fluttertoast: ^8.2.6
  retrofit: ^4.1.0
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.1
  flutter_easyloading: ^3.0.5
  flutter_spinkit: ^5.2.1
  firebase_core: ^3.3.0
  firebase_crashlytics: ^4.0.4
  firebase_auth: ^5.1.3
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.2
  build_runner: ^2.4.11
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/font/
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/font/SFProDisplay-Regular.ttf
          weight: 400
        - asset: assets/font/SFProDisplay-Medium.ttf
          weight: 500
        - asset: assets/font/SFProDisplay-Semi-Bold.ttf
          weight: 600
        - asset: assets/font/SFProDisplay-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: "assets/icon/ic_splash.png"
  image_dark: "assets/icon/ic_dark_splash.png"
  android_12:
    image: "assets/icon/ic_android_splash.png"
    image_dark: "assets/icon/ic_dark_android_splash.png"
    color: "#ffffff"
    color_dark: "#000000"
  android_gravity: fill
  fullscreen: true
  android: true
  ios: true
